#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -Ofast -I /opt/homebrew/Cellar/sdl2/2.30.1/include/ -L /opt/homebrew/Cellar/sdl2/2.30.1/lib/ source/client.c -o client -lSDL2
	clang -Ofast source/server.c -o server

elif [ "clean" = "$1" ]; then
	rm -rf client
	rm -rf client.dSYM
	rm -rf server
	rm -rf server.dSYM

elif [ "" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-poison-system-directories -Wno-padded -Wno-reserved-id-macro -fsanitize=address,undefined -I /opt/homebrew/Cellar/sdl2/2.30.1/include/ -L /opt/homebrew/Cellar/sdl2/2.30.1/lib/ source/client.c -o client -lSDL2
	clang -g -O0 -Weverything -Wno-poison-system-directories -fsanitize=address,undefined source/server.c -o server

elif [ "client" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-poison-system-directories -Wno-padded -Wno-reserved-id-macro -fsanitize=address,undefined -I /opt/homebrew/Cellar/sdl2/2.30.1/include/ -L /opt/homebrew/Cellar/sdl2/2.30.1/lib/ source/client.c -o client -lSDL2 
	
elif [ "server" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-poison-system-directories -fsanitize=address,undefined source/server.c -o server

else 
	echo "build: unknown target: $1"
fi
