#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -std=c11 -Ofast c.c -o run -mcpu=apple-m1

elif [ "general_release" = "$1" ]; then
	clang -std=c11 -Ofast c.c -o run

elif [ "clean" = "$1" ]; then
	rm -rf run
	rm -rf run.dSYM

elif [ "" = "$1" ]; then 
		clang -g -O0 -std=c11 -Weverything -Wno-declaration-after-statement -Wno-poison-system-directories -fsanitize=address,undefined c.c -o run -ferror-limit=1 

else 
	echo "build: unknown target: $1"
fi